### ISSUE TITLE
muito boa explicação sobre ubuntu 

### ISSUE THREAD

**Issue by LxNautico** [MicrosoftDocs/WSL.pt-BR#6]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Criar e atualizar contas de usuário para distribuições do Linux](https://docs.microsoft.com/pt-br/windows/wsl/user-support?redirectedfrom=MSDN)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL.pt-br/blob/live/WSL/user-support.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @LxNautico
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Olá, @LxNautico , 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
